#version: "4"
services:
  postgresql:
    image: "postgres"
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=root
        - POSTGRES_DB=order_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

#  kafka-ui:
#    container_name: kafka-ui
#    image: provectuslabs/kafka-ui:latest
#    ports:
#      - 2020:8080
#    environment:
#      DYNAMIC_CONFIG_ENABLED: true
#    volumes:
#      - ~/kui/config.yml:/etc/kafkaui/dynamic_config.yaml